/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Presence } from './presence';


export interface Admin { 
    id?: string;
    nom?: string;
    prenom?: string;
    login?: string;
    telephone?: string;
    password?: string;
    absences?: Array<Presence>;
}

