/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Etudiant } from './etudiant';


export interface Classe { 
    id?: string;
    filiere?: string;
    niveau?: string;
    etudiants?: Array<Etudiant>;
}

