/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Presence } from './presence';


export interface Cours { 
    id?: string;
    date?: string;
    nomCours?: string;
    duree?: number;
    absences?: Array<Presence>;
}

