/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Vigile { 
    id?: string;
    nom?: string;
    prenom?: string;
    login?: string;
    telephone?: string;
    password?: string;
}

