export * from './adminControllerImpl.service';
import { AdminControllerImplService } from './adminControllerImpl.service';
export * from './classeControlerImpl.service';
import { ClasseControlerImplService } from './classeControlerImpl.service';
export * from './coursControllerImpl.service';
import { CoursControllerImplService } from './coursControllerImpl.service';
export * from './etudiantControllerImpl.service';
import { EtudiantControllerImplService } from './etudiantControllerImpl.service';
export * from './justificatifControllerImpl.service';
import { JustificatifControllerImplService } from './justificatifControllerImpl.service';
export * from './presenceControllerImpl.service';
import { PresenceControllerImplService } from './presenceControllerImpl.service';
export * from './vigileControllerImpl.service';
import { VigileControllerImplService } from './vigileControllerImpl.service';
export const APIS = [AdminControllerImplService, ClasseControlerImplService, CoursControllerImplService, EtudiantControllerImplService, JustificatifControllerImplService, PresenceControllerImplService, VigileControllerImplService];
